// ADD PRODUCT
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'
export const ADD_PRODUCT_LOADING = 'ADD_PRODUCT_LOADING'
// GET PRODUCTS
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR'
export const GET_PRODUCTS_LOADING = 'GET_PRODUCT_LOADING'
// GET PRODUCT BY ID
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS'
export const GET_PRODUCT_BY_ID_ERROR = 'GET_PRODUCT_BY_ID_ERROR'
export const GET_PRODUCT_BY_ID_LOADING = 'GET_PRODUCT_BY_ID_LOADING'
// UPDATE PRODUCT
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR'
export const UPDATE_PRODUCT_LOADING = 'UPDATE_PRODUCT_LOADING'
// DELETE PRODUCT
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR'
export const DELETE_PRODUCT_LOADING = 'DELETE_PRODUCT_LOADING'
